name: paper-v4
on:
  push:
    paths: # since the paper doesn't depend on the rest of the repo
      - docs/paper-v4/**
      - .github/workflows/paper-v4.yml
    branches:
      - "*"
  workflow_dispatch:

defaults:
  run:
    shell: bash -el {0}

permissions: {}

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master # zizmor: ignore[unpinned-uses]
        with:
          journal: joss
          paper-path: docs/paper-v4/paper.md
      - name: Upload
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: paper
          path: docs/paper-v4/paper.pdf
